name: NoGhost
version: 1.0.0
main: com.noghost.NoGhost
api-version: '1.21'
author: Fast
description: Fix Ghost Hits - Paper 1.21.1

commands:
  noghost:
    description: NoGhost main command
    usage: /noghost reload
    aliases: [ng]
    permission: noghost.admin

permissions:
  noghost.admin:
    description: Access to NoGhost admin commands
    default: op
